name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies for app
      run: dotnet restore ./Src/MyApp/MyApp.csproj

    - name: Restore dependencies for tests
      run: dotnet restore ./Tests/MyAppTests/MyAppTests.csproj

    - name: Build App
      run: dotnet build ./Src/MyApp/MyApp.csproj -c Release --no-restore

    - name: Build Tests
      run: dotnet build ./Tests/MyAppTests/MyAppTests.csproj -c Debug --no-restore

    - name: Test
      run: dotnet test ./Tests/MyAppTests/MyAppTests.csproj --no-build --verbosity detailed